del htmllocal\assets\*.png
del htmllocal\pages\*.html
del htmllocal\styles\*.css
del htmllocal\scripts\*.js
rd htmllocal\assets
rd htmllocal\pages
rd htmllocal\styles
rd htmllocal\scripts
rd htmllocal